export {default as Features} from './features/Features.jsx'
export {default as Blog} from './Blog/Blog.jsx'
export {default as Footer} from './Footer/Footer.jsx'
export {default as Header} from './Header/Header.jsx'
export {default as Possibility} from './Possibility/Possibility.jsx'
export {default as WhatGPT3} from './whatGPT3/WhatGPT3.jsx'
